services:
  api:
    build: .
    container_name: coleira-tech-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ballast.proxy.rlwy.net:26163/railway
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ASAmvVZtqLtYtTBpMsaPjOwGahTfdkev
    networks:
      - coleira-network

networks:
  coleira-network:
    driver: bridge
