version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: coleira-tech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123@postgres
    volumes:
      - coleira_pgdata:/var/lib/postgresql/data
    networks:
      - coleira-network

  api:
<<<<<<< HEAD
    build: .
=======
    build: .  # Usa o Dockerfile da raiz
>>>>>>> 4716bec24a74ca121ca098416dd59df1b79f3f5e
    container_name: coleira-tech-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coleira-tech
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123@postgres
    networks:
      - coleira-network

volumes:
<<<<<<< HEAD
  pgdata:
    driver: local
    driver_opts:
      railway: "true"  # sinaliza ao Railway que esse volume é persistente
=======
  coleira_pgdata:  # nome explícito evita problemas de volume anônimo
>>>>>>> 4716bec24a74ca121ca098416dd59df1b79f3f5e

networks:
  coleira-network:
    driver: bridge
