spring.application.name=Coleira-Tech

spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:39410/railway
spring.datasource.username=postgres
spring.datasource.password=OcgOZwJoTqPkXAHtaZcKioBnuIYvKFxg
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
